language: java

jdk:
- oraclejdk8

script:
- "./gradlew test testAcceptance"

notifications:
  email:
    recipients:
    - secure: OAS+81QEM1DLfNPVgONM/SQMwlfFjEDrXuvcwLwOmVIwfN+w9FdDYt9tM/6PYscSQS4ywIDts4N3R6d/xWKuOVSE2EB2+ciOhXlW3BmYQ6Ca1li46xHHIkvL0ZzRoFC8ptnDmSktxnDwQ8Lj3ca+ToDw1L7a7pstBr9GCG8Muy84osSbP4XLb6Dfd6QimLJB8j7fRXev6LRQtxCrauKaUVPBAEkrcZ8tDNmXIdr35uk2hpiuXH15J4Snn5e+FtUpqiqnxcEsHvYeYJ0G6FqAVdXI/34zhpSiDSaKWd/hH3WkhLjY68HgKCqRktdUZCjqXS71sNt8nDJUxviGz57795iAIahLeNigU+2ELnt97CPykpK1BuAGR+W7S0X64aSx8h8TwTNKpomRw5meqCUtZzEMELQba/+6sKRUIVd37TpWUMQmRkVwwUsgfLXDldcfJ96ndHVatoGRO+r/cyZvgUI4V6QTCJ1yphrfBz6Aqz3pa7ynSMm4RuaRCQzmf+TFP20x9z3wg+JPnd8Uehs5kbGBBnBmD4Brhd/JZ+UOyB0xCO/1RqwHx5FaHpGLd47yBoXMMkQHL2nV5QE+o580RnxlrL+ZFg3hF/3xsjQ/wwSO/weReReoOPrXfkiKHoIzrkmCOtEFXMnLZ71zIdOh5Qwgd/ITS37oDMCr1VrcXxQ=
    on_success: change
    on_failure: always

deploy:
  - provider: cloudfoundry
    username:
      secure: WwCUHvTRnNYh9EzMcRva4E52Tldmk+qs1Y//toX3L7MuzRejS5zNE8BGK8cQX9xm0kL5gigF3wcOxGGKF5Y2AV3IQCudkbqn7xKnjWUH9k1dgSSzxCpu6VcApn5gvlM3YJ5q4WocX6YtPaROPIM7ZRtdU0/2UDTjqxNOxt4ve3pO5TtFTQJP9uNNL37elv9EnvzY64kSF7+H/zHBvr+kFCsbr1I7EOoc9uAAvyTeA+77BttElrZ8ahDVoNrwEAoqsqAVHZSvpofw9h3zOM0sm7LXFSxOMlDJh1DVcoJIrhw0/7woskrTGXNRTqlUj8PRJHQk69s1UPRjgv9ouFymt+G5EFm4lEe0T8Qd2V3UPTPOG0tjl5vN1iQRLb7mEOoQGGdgEN0hixkvfv64KczcdejQlAMUS9aqBlAgsftcqxm9SFmYmvQjLEaGqx4RxL/qVebFCy8fUgqGav4l+bpZZTd100DA0Pe8Xv/9OvXrBLXPpD4l9dKLmrYrl5Cc7Ok2tuIuwzS3RhJ/Ri4AkSsijpO/EOUX7XSE51Mt5ZrSzfmCMonc0+hh8Q7mSpoEhp0xY4U7d/C5lZ2GqSugxc9K6EADI+ABdfniBaXSDidKrVo/JppNIFBqgHYixyKuWjMfAe7hR1FVyL2gaGZFvx8hzWnqECrGLFMHC+xExJNe2Bw=
    password:
      secure: irJjlER2M3DnlRR6IvbT1cJ58bZtJuPzYs1tbhUTBizW1je5LiYYbafUrTmFn0fkwsWi8BcBLNzwjxFMjikZKCBNsZlaRZ+TT3WtQfvGdrRlN6N2jU65CgUEO3lnCtoBxtv1m00OJGx8XZ2J0IR0StM8TbCW8KQCNYwEddiZhgqxNjDqEncs6HkjblY+Xs3aXLiVH8E4EWUi6hzTECXEGnRT04EPun+DGd/cqCdflRWJm68b6AnZGshBUKy2pBZX2vHKoZGYPY7UeR43/ztBd6Twf9G+b9BzrA7PR7Mq8vM8uZdqwME1+5tzrLn2W4EUax3vxWM0CEy7V/qjMNxl4Cuver429qT9EGm/ZpeNLe46/B+b3txqc1qM7RVv+ppdmxTGT2gtvM14TERl9fsl2ZrSm/NQLbMdjvpo2+Dh22m9F/pnYJ6W4T2BP/B76YecvRF9XuGytw82OABQF2K3NV2dqTTcBMnnaeaaF0ULpGeZrCbIHcgLrRgVc/NInrtvcawafNi9RrhJYWsz4DxnwbT3ZV2VNMmn2A8Rq8BG3G6i0FIo6aXwzfl+vnZ5RzaYiPGdbpZmF42D9Z1EYtC3zXe+K9qUljz1uFe/icxM76pkgfUgL58DdAGmj7bivGKDBZmxHZNEM4cBBGgfIfk8yqwWeLaNfaxsyRMmOlS7ZR4=
    api: https://api.run.pivotal.io
    organization: Catulla
    space: development
#  - provider: bintray
#    file: "bintray.json"
#    user: "bu3"
#    key:
#      secure: XU+RUNIjW1nXeO20GWLXXA8sncYDG7olaa3lpo+4R8dw3WnLWiZEJUuE69QBzXlX1GSEWcoxGekYa2o2SotiyOlxecXetEONWN92aox8d93ncPJgtecUOOixFeI9rOmFkuZjotslSzo3nVXRrh1+WKrAQgyxUe3jp+Vog0fUKtLQbTCxnybjL5gai1hq1LvPjPQ3MvYbv11zfMjasLZ2XUhQw7SGDUi9FbqKsFliD/NzxpJuGkMG49P5tAIIwXIiZCgWiQpmiP9Ano2JhrA1HEus+w8R7kb4e6Jdrzp5bRuUhFu1KuJq2IOE/7eZ/d/3DCiUvKDn20Uam/9KearIfvzLZZjcu+e/PLNFE7oxh7yvu4ke4/wY2JQvtrgCjT8pg1VC/WmFSQi68J0Dvwnbl8lxdhjm0nRq3WlTMCH0+UVg26WOhu1vcjgng4hOmRBGMAWisOeBnc/ogDqz/yIncvP1n4dZ0ph+ioaQOfb9blU0JpvZs5Q5kZlHimo0oeaZy4K+v2ftykDz22XGQsBlWpTc4MYeuYQHB27YKfk6sZPwgNBSjwRkeE2AXpjDFKFtHhEhnfJcunyKNcH31X4vvliFyLekISZV3DeKjC1O4s6MJ4zargVtivdh1fcTP5sNOoriK/sVJJgI2psqSCV/k9w6hcQrm6CLMZzYxOoRXqs=